#+TITLE: Emacs configuration
#+PROPERTY: header-args:emacs-lisp :tangle ~/.config/emacs/init.el :mkdirp yes
#+STARTUP: overview

* COMMENT Notes

- Split org export stuff into its own package so it can be used independently (e.g. in CI)
- Switch to =elpaca= for package management
- Use org for logic (tables, scripts etc), but =load-file= instead of large elisp blocks
- Consider =meow= instead of =evil=
- Replace =ivy + swiper + counsel= with =vertico + consult + orderless + embark + marginalia=
- Completion: Replace =company= with =corfu + cape + nerd-icons-corfu=. Built-in =completion-preview-mode=? =prescient=?
- Fix =no-littering=
- Compare =punch-line= with =doom-modeline=
- =colorful-mode= looks more useful than =rainbow-mode=
- try =eglot= over =lsp-mode=
- use =diff-hl= over =git-gutter=
- consider newish built-in =project.el= over =projectile=
- =treesitter + combobulate=

** Things to add

- check out new (30.1) touch screen & Android support
- =helpful=
  - =discover.el=
- take some ideas from =org-modern=
- =forge= (=magit= for GitHub / GitLab etc)
  - dashboard (=emacs-dashboard=, =enlight=)
- relative line numbers (=linum-relative=)
- modern scrollbar (=yascroll=)
  - =dimmer.el= (dim inactive panes)
- =typo.el= (easy entering of dashes and quotes)
- =whitespace-cleanup-mode=
- =treesit-fold=
- =dirvish= (extended dired)
- lisp editing improvements:
  =paredit elsa ellsp highlight-defined elmacro suggest.el easy-escape eros elisp-autofmt=
- =paredit= for lisp editing
- =auto-dark= theme switching

* Setup
** No littering

Early init:
#+begin_src emacs-lisp :tangle ~/.config/emacs/early-init.el
  (defvar user-emacs-cache-directory "~/.cache/emacs/"
    "Directory for Emacs cache files that can be deleted without loss of information.")
  (defvar user-emacs-config-directory "~/.config/emacs/"
    "Directory for Emacs user configuration files.")
  (defvar user-emacs-data-directory "~/.local/share/emacs/"
    "Directory for Emacs user data and Lisp files. This also sets \\[user-emacs-directory].")

  (setf user-emacs-directory user-emacs-data-directory)
  ;; Change native compilation cache location.
  (when (and (fboundp #'startup-redirect-eln-cache)
             (fboundp #'native-comp-available-p)
	     (native-comp-available-p))
    (startup-redirect-eln-cache
     (convert-standard-filename
      (expand-file-name "var/eln-cache/" user-emacs-data-directory))))

  (setq custom-file (expand-file-name "custom.el" user-emacs-config-directory))
#+end_src

After package manager:
#+begin_src emacs-lisp :tangle no :noweb-ref post-packagemanager
  ;; As early as possible in init.el, but after setting up the package manager
  (use-package no-littering
    :config
    ;; Centralise backups, excluding some temporary directories.
    (no-littering-theme-backups)
    ;; Centralise lock files.
    ;; May cause problems if multiple people access a file simultaneously on different systems.
    (let ((dir (no-littering-expand-var-file-name "lock-files/")))
      (make-directory dir t)
      (setq lock-file-name-transforms `((".*" ,dir t)))))

  (elpaca-process-queues)

  (use-package recentf
    :ensure nil
    :config
    (add-to-list 'recentf-exclude
                 (recentf-expand-file-name no-littering-var-directory))
    (add-to-list 'recentf-exclude
  	       (recentf-expand-file-name no-littering-etc-directory)))

  (add-hook 'elpaca-after-init-hook (lambda () (load custom-file 'noerror)))
  #+end_src
#+end_src

** Package management

#+begin_src emacs-lisp :tangle ~/.config/emacs/early-init.el
  (setq package-enable-at-startup nil)
#+end_src

#+begin_src emacs-lisp :noweb yes
  (defvar elpaca-installer-version 0.11)
  (defvar elpaca-directory (expand-file-name "elpaca/" user-emacs-data-directory))
  (defvar elpaca-builds-directory (expand-file-name "builds/" elpaca-directory))
  (defvar elpaca-repos-directory (expand-file-name "repos/" elpaca-directory))
  (defvar elpaca-order '(elpaca :repo "https://github.com/progfolio/elpaca.git"
                                :ref nil :depth 1 :inherit ignore
                                :files (:defaults "elpaca-test.el" (:exclude "extensions"))
                                :build (:not elpaca--activate-package)))
  (let* ((repo  (expand-file-name "elpaca/" elpaca-repos-directory))
         (build (expand-file-name "elpaca/" elpaca-builds-directory))
         (order (cdr elpaca-order))
         (default-directory repo))
    (add-to-list 'load-path (if (file-exists-p build) build repo))
    (unless (file-exists-p repo)
      (make-directory repo t)
      (when (<= emacs-major-version 28) (require 'subr-x))
      (condition-case-unless-debug err
          (if-let* ((buffer (pop-to-buffer-same-window "*elpaca-bootstrap*"))
                    ((zerop (apply #'call-process `("git" nil ,buffer t "clone"
                                                    ,@(when-let* ((depth (plist-get order :depth)))
                                                       (list (format "--depth=%d" depth) "--no-single-branch"))
                                                    ,(plist-get order :repo) ,repo))))
                    ((zerop (call-process "git" nil buffer t "checkout"
                                          (or (plist-get order :ref) "--"))))
                    (emacs (concat invocation-directory invocation-name))
                    ((zerop (call-process emacs nil buffer nil "-Q" "-L" "." "--batch"
                                          "--eval" "(byte-recompile-directory \".\" 0 'force)")))
                    ((require 'elpaca))
                    ((elpaca-generate-autoloads "elpaca" repo)))
              (progn (message "%s" (buffer-string)) (kill-buffer buffer))
            (error "%s" (with-current-buffer buffer (buffer-string))))
        ((error) (warn "%s" err) (delete-directory repo 'recursive))))
    (unless (require 'elpaca-autoloads nil t)
      (require 'elpaca)
      (elpaca-generate-autoloads "elpaca" repo)
      (let ((load-source-file-function nil)) (load "./elpaca-autoloads"))))
  (add-hook 'after-init-hook #'elpaca-process-queues)
  (elpaca `(,@elpaca-order))

  (elpaca elpaca-use-package (elpaca-use-package-mode))
  (elpaca-wait) ;; wait until elpaca-use-package is loaded before using it

  (setq use-package-always-ensure t)

  <<post-packagemanager>>

  (elpaca-wait)
#+end_src

* User interface
** Aesthetics
** Keybindings

#+begin_src emacs-lisp
  (use-package which-key
    :ensure nil :after evil
    :custom (which-key-idle-delay 0.3)
    :config (which-key-mode))
#+end_src

To enable mapping =jk= to escape, we use the =:chords= keyword from =use-package-chords=.
This needs to be enabled early in =init.el= so that we can run =elpaca-wait= before using it.

#+begin_src emacs-lisp :tangle no :noweb-ref post-packagemanager
  (use-package use-package-chords :config (key-chord-mode))
#+end_src

*** Evil

#+begin_src emacs-lisp
  (use-package evil
    :demand t
    :init
    (setq evil-want-keybinding nil) ;; disable poor man's evil-collection
    :chords
    (("jk" . evil-normal-state))
    :custom
    (evil-move-cursor-back nil) ;; keep cursor in place on leaving insert state
    (evil-want-Y-yank-to-eol 1) ;; instead of Y yanking the whole line
    (evil-undo-system #'undo-redo) ;; instead of Y yanking the whole line
    :config
    (evil-mode))

  (use-package evil-collection
    :after evil
    :config (evil-collection-init))

  ;; More ergonomic access to modifier keybindings
  ;; SPC x -> C-x C-... (press SPC again to cancel C-)
  ;; SPC c -> C-c C-... (press SPC again to cancel C-)
  ;; SPC h -> C-h
  ;; SPC m -> M-...; SPC M -> C-M-...
  ;; SPC _ -> C-c ...
  (use-package evil-keypad
   :after evil
   :bind
   (:map evil-keypad-state-keymap ("C-h" . #'describe-keymap))
   :custom (evil-keypad-C-M-trigger ?M)
   :config (evil-keypad-global-mode))
#+end_src

** Completion

**** Built-in options

#+begin_src emacs-lisp
  (use-package emacs
    :ensure nil
    :custom
    (enable-recursive-minibuffers t)
    ;; I don't completely understand what cursor-intangible-mode changes here,
    ;; but it seems to be recommended in the Vertico docs.
    (minibuffer-prompt-properties
     '(read-only t cursor-intangible t face minibuffer-prompt))
    ;; Hide commands which do not work in the current mode.
    (read-extended-command-predicate #'command-completion-default-include-p)
    (completion-ignore-case t))

  ;; Persist minibuffer history over restarts.
  (use-package savehist
    :ensure nil
    :config (savehist-mode))
#+end_src

**** [[https://github.com/minad/vertico][Vertico]]: VERTical Interactive COmpletion

#+begin_src emacs-lisp
  ;; VERTical Interactive COmpletion
  (use-package vertico
    :bind
    (:map vertico-map
  	("C-j" . #'vertico-next)
  	("C-k" . #'vertico-previous))
    :config
    (vertico-mode)
    (vertico-multiform-mode)
    (vertico-mouse-mode))

  (use-package vertico-directory
    :ensure nil  ;; part of vertico
    :hook
    ;; Make .../~ instantly replace a file path with ~/.
    (rfn-eshadow-update-overlay . vertico-directory-tidy)
    :custom
    (vertico-multiform-categories
      ;; Backspace enters parent directory.
      '((file (:keymap . vertico-directory-map)))))
#+end_src

**** [[https://github.com/minad/orderless][Orderless]] (fancy pattern matching)

Orderless divides search patterns into orderless space-separated segments, and provides bangs like
- =,= to match initials
- =^= to match the beginning of an item
- =!= for negation.

#+begin_src emacs-lisp
  (use-package orderless
    :custom
    (completion-styles '(orderless basic)) ; enable orderless
    (completion-category-overrides
     ;; TRAMP hostname completion requires `basic' to be tried first.
     ;; `partial-completion' allows wildcards and things like /u/s/l ->
     ;; /usr/share/local
     '((file (styles basic partial-completion)))))
#+end_src

**** [[https://github.com/minad/marginalia][Marginalia]]

#+begin_src emacs-lisp
  (use-package marginalia
    :config (marginalia-mode))
#+end_src

**** [[https://github.com/minad/consult][Consult]]

#+begin_src emacs-lisp
  (use-package consult
    :bind
    (("C-c b" . #'consult-buffer)
     :prefix-map quark/search-prefix-map :prefix "C-c f"
     ("l" . #'consult-line)
     ("r" . #'consult-ripgrep)
     ("R" . #'consult-grep)
     ("f" . #'consult-fd)
     ("F" . #'consult-find)
     :prefix-map quark/settings-prefix-map :prefix "C-c s"
     ("t" . #'consult-theme)
     :prefix-map quark/ide-prefix-map :prefix "C-c l"
     ("e" . #'consult-error)
     ("x" . #'consult-xref)
     :prefix-map quark/org-prefix-map :prefix "C-c o"
     ("o" . #'consult-org-heading))
    :custom
    (xref-show-xrefs-function #'consult-xref)
    (xref-show-definitions-function #'consult-cref))
#+end_src

* Writing
** General
** Org
** LaTeΧ
** Org LaTeΧ export

* Programming
** General
** Emacs lisp
** Nix
** Haskell
** Python
** Shell
** Web development

* Features
** Git integration

#+begin_src emacs-lisp
  ;; Magit requires transient v0.9.3, but built-in is currently v0.7.2.2
  (use-package transient)

  (use-package magit
    :after transient
    :init
    (setq forge-add-default-bindings nil)
    (setq forge-add-default-sections nil)
    :bind
    (:prefix-map quark/vc-prefix-map :prefix "C-c g"
     ("g" . #'magit-status)))

  ;; Not usable until I've set up an access token.
  (use-package forge
    :after magit)
#+end_src

** Dired
** Projects

Too many weird bugs trying to replace [[kbd:C-x p]] with [[kbd:C-c p]] (for fewer keystrokes using =evil-keypad=).
Most of the time I've just not been able to get another key to call =project-prefix-map= at all.
Sometimes I've made that work, but then [[kbd:p]] calls =project-prefix-map= in /insert state/, instead of actually inserting the letter =p=!
I can't even figure out how do do this using =general.el=.

Probably this means its best to just define a new prefix from scratch.
#+begin_src emacs-lisp
  (use-package project
    :ensure nil
    :bind
    (("C-c SPC" . #'project-find-file)
     :prefix-map quark/project-prefix-map :prefix "C-c p"
     ("p" . #'project-switch-project)))
#+end_src

* Miscellany
