# See
# https://erick.navarro.io/blog/auto-build-and-publish-emacs-org-configuration-as-a-website/

name: CI

on:
  push:
    branches:
      - master
    paths:
      - .config/emacs/**
      - .github/**

jobs:
  build-literate-config-html:
    runs-on: ubuntu-latest
    container: alpine:3.13.4
    steps:
      - uses: actions/checkout@v2
      - name: Install emacs-nox
        run: apk --update add emacs
      - name: Export literate configuration to HTML
        run: cd .github/scripts && sh export-dotfiles-org-to-html
      - name: Push to destination repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
        with:
          source-directory: '.github/output'
          destination-github-username: 'quarkQuark'
          destination-repository-name: 'literate-config'
          user-email: bot@emacs.bot
